# Generated by Django 2.2.7 on 2019-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnedayClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='클래스명')),
                ('image', models.ImageField(upload_to='class/img/', verbose_name='사진')),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='종료 날짜')),
                ('place', models.CharField(max_length=50, verbose_name='장소')),
                ('price', models.CharField(max_length=30, verbose_name='비용')),
                ('sns', models.CharField(help_text='SNS 아이디를 입력해주세요', max_length=100, verbose_name='SNS 아이디')),
                ('description', models.TextField(verbose_name='간단한 설명')),
            ],
        ),
    ]
