# Generated by Django 2.2.7 on 2019-11-27 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onedayclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnedayClassReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('onedayclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onedayclass_reviews', to='onedayclass.OnedayClass')),
            ],
        ),
    ]
