# Generated by Django 2.2.7 on 2019-11-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
