# Generated by Django 2.2.7 on 2019-12-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0002_center_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='자격증')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('phone', models.CharField(help_text='-없이 입력해주세요.', max_length=11, verbose_name='전화번호')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='성별')),
                ('greeting', models.CharField(max_length=100, null=True, verbose_name='간단한 인사말')),
                ('image', models.ImageField(upload_to='instructor/img/', verbose_name='사진')),
                ('schedule', models.ImageField(help_text='개인스케줄표를 이미지로 업로드해주세요.', null=True, upload_to='instructor/schedule/', verbose_name='개인스케줄')),
                ('sns_url', models.URLField(help_text='SNS주소를 입력해주세요', max_length=250, verbose_name='SNS주소')),
                ('center', models.ManyToManyField(blank=True, help_text='소속되어있거나 관계되어있는 센터들을 선택해주세요.', to='center.Center', verbose_name='센터')),
                ('certificate', models.ManyToManyField(to='instructor.Certificate', verbose_name='보유자격증')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='필라테스기구')),
            ],
        ),
        migrations.CreateModel(
            name='VisitingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=10, verbose_name='방문가능지역')),
            ],
        ),
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='요가종류')),
            ],
        ),
        migrations.CreateModel(
            name='YogaInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(choices=[('A', '6개월 미만'), ('B', '6개월 이상 1년 미만'), ('C', '1년 이상 3년 미만'), ('D', '3년 이상')], default='A', max_length=1, verbose_name='경력')),
                ('price', models.TextField(verbose_name='가격')),
                ('instructor', models.ForeignKey(help_text='요가강사의 이름을 선택해주세요.', on_delete=django.db.models.deletion.CASCADE, related_name='yoga_instructor', to='instructor.Instructor', verbose_name='이름')),
                ('style', models.ManyToManyField(blank=True, to='instructor.Yoga', verbose_name='가능한 요가 종류')),
            ],
        ),
        migrations.CreateModel(
            name='VisitingInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(choices=[('A', '6개월 미만'), ('B', '6개월 이상 1년 미만'), ('C', '1년 이상 3년 미만'), ('D', '3년 이상')], default='A', max_length=1, verbose_name='경력')),
                ('price', models.TextField(verbose_name='가격')),
                ('instructor', models.ForeignKey(help_text='방문수업강사의 이름을 선택해주세요.', on_delete=django.db.models.deletion.CASCADE, related_name='visiting_instructor', to='instructor.Instructor', verbose_name='이름')),
                ('instrument', models.ManyToManyField(blank=True, to='instructor.Instrument', verbose_name='필라테스 기구')),
                ('visiting_area', models.ManyToManyField(blank=True, help_text='방문수업이 가능한 지역을 선택해주세요.', to='instructor.VisitingArea', verbose_name='방문가능지역')),
            ],
        ),
        migrations.CreateModel(
            name='PilatesInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(choices=[('A', '6개월 미만'), ('B', '6개월 이상 1년 미만'), ('C', '1년 이상 3년 미만'), ('D', '3년 이상')], default='A', max_length=1, verbose_name='경력')),
                ('price', models.TextField(verbose_name='가격')),
                ('instructor', models.ForeignKey(help_text='필라테스강사의 이름을 선택해주세요.', on_delete=django.db.models.deletion.CASCADE, related_name='pilates_instructor', to='instructor.Instructor', verbose_name='이름')),
            ],
        ),
    ]
