# Generated by Django 2.2.7 on 2019-11-24 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='센터명')),
                ('image1', models.ImageField(null=True, upload_to='center/img/', verbose_name='센터 사진1')),
                ('image2', models.ImageField(null=True, upload_to='center/img/', verbose_name='센터 사진2')),
                ('image3', models.ImageField(null=True, upload_to='center/img/', verbose_name='센터 사진3')),
                ('event', models.ImageField(null=True, upload_to='center/event/', verbose_name='이벤트')),
                ('price', models.TextField(verbose_name='이용가격')),
                ('info', models.TextField(verbose_name='이용정보')),
                ('schedule', models.ImageField(help_text='스케줄표를 이미지로 업로드해주세요', null=True, upload_to='center/schedule/', verbose_name='스케줄표')),
                ('phone', models.CharField(max_length=20, verbose_name='센터 전화번호')),
                ('address', models.CharField(max_length=200, verbose_name='센터 주소')),
                ('site', models.URLField(max_length=250, verbose_name='센터 사이트 주소')),
            ],
        ),
        migrations.CreateModel(
            name='CenterReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_reviews', to='center.Center')),
            ],
        ),
    ]
